[tools]
node = "20.19.0"
java = "temurin-17"
npm = "latest"
"npm:firebase-tools" = "15.0.0"

[tasks.deploy-functions]
description = "ðŸš€Cloud Functions ã‚’ãƒ‡ãƒ—ãƒ­ã‚¤"
run = "firebase deploy --only functions"

[tasks.deploy-rules]
description = "ðŸš€ Firestore Rules ã‚’ãƒ‡ãƒ—ãƒ­ã‚¤"
run = "firebase deploy --only firestore:rules"
